name: springwolf-sqs

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/springwolf-sqs.yml'
      - 'springwolf-sqs/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew -p springwolf-sqs-plugin build

      - name: Run integration tests
        run: ./gradlew -p springwolf-sqs-example test
